// <auto-generated />
using System;
using HW1API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW1API.Migrations
{
    [DbContext(typeof(HomeworkDbContext))]
    [Migration("20230926003733_AddedConnectionsandReview")]
    partial class AddedConnectionsandReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("HW1API.Entities.Connection", b =>
                {
                    b.Property<int>("ConnectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConnectionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionID");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("HW1API.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonSubject")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LessonId");

                    b.ToTable("LessonChart");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            LessonSubject = "API Construction"
                        },
                        new
                        {
                            LessonId = 2,
                            LessonSubject = "Security Developement"
                        },
                        new
                        {
                            LessonId = 3,
                            LessonSubject = "Decision Tables"
                        },
                        new
                        {
                            LessonId = 4,
                            LessonSubject = "Free Space"
                        },
                        new
                        {
                            LessonId = 5,
                            LessonSubject = "Dont Steal My Nachos"
                        });
                });

            modelBuilder.Entity("HW1API.Entities.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AForthThing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ReviewTime")
                        .HasColumnType("REAL");

                    b.Property<int>("TempleteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewID");

                    b.HasIndex("ConnectionID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HW1API.Entities.Template", b =>
                {
                    b.Property<int>("TempleteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("TrueValue")
                        .HasColumnType("REAL");

                    b.HasKey("TempleteID");

                    b.ToTable("Table Example");

                    b.HasData(
                        new
                        {
                            TempleteID = 1,
                            Name = "First Template",
                            TrueValue = 11.34f
                        },
                        new
                        {
                            TempleteID = 2,
                            Name = "Template B",
                            TrueValue = 27.63f
                        },
                        new
                        {
                            TempleteID = 3,
                            Name = "Mega Template",
                            TrueValue = 19.87f
                        },
                        new
                        {
                            TempleteID = 4,
                            Name = "Newborn Template",
                            TrueValue = 3.21f
                        },
                        new
                        {
                            TempleteID = 5,
                            Name = "Template Regret",
                            TrueValue = 88.88f
                        });
                });

            modelBuilder.Entity("HW1API.Entities.Review", b =>
                {
                    b.HasOne("HW1API.Entities.Connection", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ConnectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HW1API.Entities.Connection", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
